apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dotnet-scale-poc
  namespace: artur-guttman-dev
  labels:
    app: dotnet-scale-poc
spec:
  to:
    kind: Service
    name: dotnet-scale-poc
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
